services:
  _defaults:
    autoconfigure: true
    public: false
    autowire: true

  Rinsvent\IfModifiedSinceBundle\Service\:
    resource: ../../Service/

  Rinsvent\IfModifiedSinceBundle\EventListener\IfModifiedSinceListener:
    bind:
      ttl: 3600
    tags:
      - { name: kernel.event_listener, event: kernel.request }
